# -*- coding: utf-8 -*-
"""combine_clean_chat_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1maOoTvVONSl3mPrXP3NMBLtCkOu_MHQg
"""

import json

# Load the dataset
with open("multilingual_chat_40k_dataset.json", "r", encoding="utf-8") as f:
    data = json.load(f)

# Filter and clean the prompt-response pairs
cleaned_conversations = []
for entry in data:
    prompt = entry.get("prompt", "").strip()
    response = entry.get("response", "").strip()
    if prompt and response:
        cleaned_conversations.append(f"{prompt}\n{response}\n")

# Combine all into one text block
combined_text = "\n".join(cleaned_conversations)

combined_text

# Save to a .txt file
with open("cleaned_combined_chat_data.txt", "w", encoding="utf-8") as f:
    f.write(combined_text)

print("✅ Cleaned and combined text file created: cleaned_combined_chat_data.txt")